on: [push, workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Transform SVGs
    steps:
      - uses: actions/checkout@v4
      - name: Transform SVGs
        id: transform
        uses: fallbackerik/transform-svg-action@main
      - name: List the generated files
        run: echo "The files generated are ${{ steps.transform.outputs.svgs-modified }}"
