on: [push, workflow_dispatch]

jobs:
  test_transform_job:
    runs-on: ubuntu-latest
    name: A job that runs the transform script on some test data
    steps:
      - name: Transform SVGs
        id: transform
        uses: fallbackerik/transform-svg-action@main
      - name: List generated files
        run: echo "The following files have been generated: ${{ steps.transform.outputs.svgs-modified }}"
