on: [push, workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: fallbackerik/transform-svg-action@main
      - name: Get the output time
        run: echo "The files generated are ${{ steps.hello.outputs.svgs-modified }}"
